### ISSUE TITLE
NPE - Vanilla Potion Bar Render

### ISSUE THREAD

**Issue by Fortist** [mccreery/better-hud#43]
I added this to my fairly large modpack and I get this crash with it.
Im starting to try and troubleshoot it, but I have no real idea what could cause it.
```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2019-01-18 17:42:54 EST
Description: Unexpected error

java.lang.NullPointerException
    at jobicade.betterhud.element.vanilla.PotionBar.render(PotionBar.java:76)
    at jobicade.betterhud.element.HudElement.tryRender(HudElement.java:268)
    at jobicade.betterhud.element.HudElement.renderAll(HudElement.java:284)
    at jobicade.betterhud.events.RenderEvents.renderOverlay(RenderEvents.java:139)
    at jobicade.betterhud.events.RenderEvents.onRenderTick(RenderEvents.java:62)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2511_RenderEvents_onRenderTick_Pre.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907)
    at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:119)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1098)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by mccreery** [comment]
I actually happened to catch and fix this one just a couple of commits after beta.2. If you want the fix quickly, you can clone and run `./gradlew build` and find the jar in build/libs.
