### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Yonk316** [mccreery/better-hud#47]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 1/21/19 2:28 PM
Description: Ticking entity

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source)
	at jobicade.betterhud.util.MathUtil.randomRange(MathUtil.java:74)
	at jobicade.betterhud.util.MathUtil.randomPoint(MathUtil.java:87)
	at jobicade.betterhud.element.particles.ParticleBase.createRandom(ParticleBase.java:35)
	at jobicade.betterhud.element.particles.BloodSplatters.onEntityDamage(BloodSplatters.java:37)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_251_BloodSplatters_onEntityDamage_LivingDamageEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingDamage(ForgeHooks.java:604)
	at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1128)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:926)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645)
	at net.minecraft.entity.monster.EntityMob.func_70652_k(EntityMob.java:99)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Random.nextInt(Unknown Source)
	at jobicade.betterhud.util.MathUtil.randomRange(MathUtil.java:74)
	at jobicade.betterhud.util.MathUtil.randomPoint(MathUtil.java:87)
	at jobicade.betterhud.element.particles.ParticleBase.createRandom(ParticleBase.java:35)
	at jobicade.betterhud.element.particles.BloodSplatters.onEntityDamage(BloodSplatters.java:37)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_251_BloodSplatters_onEntityDamage_LivingDamageEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingDamage(ForgeHooks.java:604)
	at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1128)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:926)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645)
	at net.minecraft.entity.monster.EntityMob.func_70652_k(EntityMob.java:99)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: minecraft:vindication_illager (net.minecraft.entity.monster.EntityVindicator)
	Entity ID: 6161
	Entity Name: Vindicator
	Entity's Exact location: -109.07, 62.85, 31.11
	Entity's Block location: World: (-110,62,31), Chunk: (at 2,3,15 in -7,1; contains blocks -112,0,16 to -97,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: -0.19, -0.45, -0.01
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: SMW 90000
	All players: 1 total; [EntityPlayerMP['Sabrina'/1270, l='SMW 90000', x=-108.38, y=62.00, z=30.95]]
	Chunk stats: ServerChunkCache: 359 Drop: 0
	Level seed: -3696302784634010231
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-40,64,20), Chunk: (at 8,4,4 in -3,1; contains blocks -48,0,16 to -33,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 4311 game time, 4311 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 157146168 bytes (149 MB) / 790052864 bytes (753 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2808 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version       | Source                                        | Signature                                |
	|:------ |:-------------------- |:------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2        | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                  | 9.42          | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                  | 8.0.99.99     | forge-1.12.2-14.23.5.2808.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2808  | forge-1.12.2-14.23.5.2808.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | foamfixcore          | 7.7.4         | minecraft.jar                                 | None                                     |
	| LCHIJA | uncraftingtable      | 1.8-beta6     | [1.12]UncraftingTable-1.8-beta6.jar           | None                                     |
	| LCHIJA | baubles              | 1.5.2         | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | betteranimalsplus    | 4.1.0         | betteranimalsplus-4.1.0.jar                   | None                                     |
	| LCHIJA | betterhud            | 1.4-beta.3    | betterhud-1.12.2-1.4-beta.3.jar               | None                                     |
	| LCHIJA | tile_booster         | 0.5           | Block Booster-1.12.2-0.5.jar                  | None                                     |
	| LCHIJA | bookshelf            | 2.3.570       | Bookshelf-1.12.2-2.3.570.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | cfm                  | 6.2.0         | cfm-6.2.0-mc1.12.2.jar                        | None                                     |
	| LCHIJA | classiccombat        | 1.0.0         | ClassicCombat-1.12-1.0.0.jar                  | None                                     |
	| LCHIJA | clumps               | 3.1.1         | Clumps-3.1.1.jar                              | None                                     |
	| LCHIJA | customstartinggear   | 1.2.0         | CustomStartingGear-1.12-1.2.0.9-universal.jar | None                                     |
	| LCHIJA | jei                  | 4.14.4.259    | jei_1.12.2-4.14.4.259.jar                     | None                                     |
	| LCHIJA | cyclicmagic          | 1.17.14       | Cyclic-1.12.2-1.17.14.jar                     | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
	| LCHIJA | eplus                | 5.0.175       | EnchantingPlus-1.12.2-5.0.175.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | golems               | 7.1.0         | ExtraGolems-1.12-7.1.0.jar                    | None                                     |
	| LCHIJA | foamfix              | 0.10.3-1.12.2 | foamfix-0.10.3-1.12.2.jar                     | None                                     |
	| LCHIJA | globalgamerules      | 2.2           | GlobalGameRules-1.12.2-2.2.7.jar              | None                                     |
	| LCHIJA | grimoireofgaia       | 1.6.8         | GrimoireOfGaia3-1.12.2-1.6.8.jar              | None                                     |
	| LCHIJA | ichunutil            | 7.1.4         | iChunUtil-1.12.2-7.1.4.jar                    | None                                     |
	| LCHIJA | hats                 | 7.0.0         | Hats-1.12.2-7.0.2.jar                         | None                                     |
	| LCHIJA | justenoughbuttons    | 1.12-1.2      | justenoughbuttons-1.12.2-1.2.3.jar            | None                                     |
	| LCHIJA | wackyguesses         | 1.0           | JWG_Emerald_1.12.2.jar                        | None                                     |
	| LCHIJA | kotlin3              | 1.1.0         | kotlin3_1.12.2-1.1.0.jar                      | None                                     |
	| LCHIJA | lucky                | 7.5.0         | LuckyBlock_1-12_v7-5-0.zip                    | None                                     |
	| LCHIJA | mclib                | 1.0           | mclib-1.0-1.12.2.jar                          | None                                     |
	| LCHIJA | metamorph            | 1.1.7         | metamorph-1.1.7-1.12.2.jar                    | None                                     |
	| LCHIJA | morefood2            | 1.1.0         | morefood2_1.12.2-1.1.0.jar                    | None                                     |
	| LCHIJA | mousetweaks          | 2.9           | MouseTweaks-2.9-mc1.12.2.jar                  | None                                     |
	| LCHIJA | placebo              | 1.5.0         | Placebo-1.12.2-1.5.0.jar                      | None                                     |
	| LCHIJA | rationcraft          | 1.0           | Rationcraft_B1.0.1_1.12.2.jar                 | None                                     |
	| LCHIJA | seeddrop             | 1.2.1-1.12    | SeedDrop-1.2.1-1.12.jar                       | None                                     |
	| LCHIJA | soulbottle           | 1.1           | soulbottle-1.12.2-1.1.jar                     | None                                     |
	| LCHIJA | spectrite            | 1.7.1         | spectrite-1.7.1.jar                           | 00119cfc089819bbcd2f9166a50c7f3df88ded78 |
	| LCHIJA | treechopper          | 1.2.4         | TreeChopper-1.12.2-1.2.4.jar                  | None                                     |
	| LCHIJA | uteamcore            | 2.2.4.94      | u_team_core-1.12.2-2.2.4.94.jar               | None                                     |
	| LCHIJA | ultimate_unicorn_mod | 1.5.16        | ultimate_unicorn_mod-1.12.2-1.5.16.jar        | None                                     |
	| LCHIJA | usefulbackpacks      | 1.3.1.13      | useful_backpacks-1.12.2-1.3.1.13.jar          | None                                     |
	| LCHIJA | wards                | 1.1           | wards-1.1.jar                                 | None                                     |
	| LCHIJA | xaerominimap         | 1.15.9        | Xaeros_Minimap_1.15.9_Forge_1.12.jar          | None                                     |

	Loaded coremods (and transformers): 
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Sabrina'/1270, l='SMW 90000', x=-108.38, y=62.00, z=30.95]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by mattrix444** [comment]
is this crash report still relevant? just curious as i was about to create a new issue regarding the same crash.

**Comment by mccreery** [comment]
No, the crash has been fixed (which is why it's closed). The next release will include the fix. Thanks.
